[theme]
name = "gruvbox"
auto_switch = false

[ui]
status_indicators = "symbols"
host_cursor = "native"

show_agent_labels_on_pane_borders = true
agent_panel_sort = "priority"
[ui.toast]
delivery = "terminal"

[keys]
prefix = "ctrl+f"

[[keys.command]]
key = "prefix+backslash"
type = "shell"
command = '"$HERDR_BIN_PATH" pane zoom --pane "$HERDR_ACTIVE_PANE_ID" --toggle'
description = "toggle pane zoom"
