function tide-save-config --description "Dump tide settings to conf.d/tide.fish so git carries them"
    set -l target $__fish_config_dir/conf.d/tide.fish

    # Tide stores its settings as universal variables in fish_variables, which
    # is gitignored as volatile state, so on its own the prompt config never
    # reaches another machine. This dumps every tide_* universal into a tracked
    # conf.d file as globals. fish prefers a global over a universal of the
    # same name, so after a git pull the file wins over whatever the local
    # wizard last stored.
    #
    # The same preference means a later `tide configure` appears to do nothing:
    # it writes universals that the file's globals shadow. Running this again
    # captures the wizard's result -- the globals are dropped for this session
    # first so the dump reads what the wizard actually stored.
    for v in (set --global --names | string match --entire -r '^tide_')
        set -eg $v
    end

    begin
        echo "# Generated by tide-save-config -- do not edit by hand."
        echo "# Mirrors the tide_* universal variables as globals so git carries the"
        echo "# prompt config; fish_variables itself stays gitignored. After running"
        echo "# 'tide configure', run tide-save-config again to refresh this file."
        for v in (set --universal --names | string match --entire -r '^tide_')
            set -l vals $$v
            if set -q vals[1]
                echo set -g $v (string escape -- $vals)
            else
                echo set -g $v
            end
        end
    end >$target

    source $target
    echo "Wrote" (count (string match -r '^set -g' <$target)) "settings to $target"
end
